# Generated by Django 2.1.5 on 2019-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20190123_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
