# Generated by Django 2.1.5 on 2019-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_marksentrydetail_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examterm',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marksentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marksentrydetail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
