# Generated by Django 2.1.5 on 2019-02-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductCategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.VendorModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
