# Generated by Django 2.1.5 on 2019-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teststudent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
