# Generated by Django 2.1.5 on 2019-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20190123_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
