# Generated by Django 2.1.5 on 2019-02-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('accounting', '0004_feeallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('mode_of_payment', models.IntegerField(choices=[(1, 'CASH'), (2, 'DEPOSIT'), (3, 'CHEQUE')])),
                ('receipt_number', models.IntegerField()),
                ('remarks', models.TextField(max_length=500)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.FeeCategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
