# Generated by Django 2.1.5 on 2019-02-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('accounting', '0006_auto_20190210_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('mode_of_payment', models.IntegerField(choices=[(1, 'CASH'), (2, 'DEPOSIT'), (3, 'CHEQUE')])),
                ('receipt_number', models.IntegerField()),
                ('remarks', models.TextField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentpaid',
            name='fee_allocation',
        ),
        migrations.RenameField(
            model_name='studentpayment',
            old_name='receipt_number',
            new_name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='student',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='fee_allocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.FeeCategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentPaid',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='fee_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.FeeCollection'),
            preserve_default=False,
        ),
    ]
