# Generated by Django 2.1.5 on 2019-02-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20190211_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='fee_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.FeeAllocation'),
        ),
    ]
