# Generated by Django 2.1.5 on 2019-02-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20190215_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Fully PAID'), (2, 'PARTIALLY PAID'), (3, 'PAID IN ADVANCE')]),
        ),
    ]
