# Generated by Django 2.1.5 on 2019-02-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190215_0724'),
        ('accounting', '0011_auto_20190217_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='student',
        ),
        migrations.RenameField(
            model_name='studentpayment',
            old_name='paid_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='fee_collection',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'DUE'), (2, 'PAID')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='receipt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='remarks',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeeCollection',
        ),
    ]
