# Generated by Django 2.1.5 on 2019-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_remove_studentpayment_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Fully PAID'), (2, 'PARTIALLY PAID'), (3, 'PAID IN ADVANCE'), (4, 'DUE')]),
        ),
    ]
